// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4kdKa-49djFcvG-KfnGsfpvua5chCa_g',
    appId: '1:65617778915:web:832d76631ab5f7240f4dd6',
    messagingSenderId: '65617778915',
    projectId: 'uber-58114',
    authDomain: 'uber-58114.firebaseapp.com',
    databaseURL: 'https://uber-58114.firebaseio.com',
    storageBucket: 'uber-58114.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGmAfXGHcZVDWPx6DnE5oZgyA-RH5FYWo',
    appId: '1:65617778915:android:7e2c75a344fb51bb0f4dd6',
    messagingSenderId: '65617778915',
    projectId: 'uber-58114',
    databaseURL: 'https://uber-58114.firebaseio.com',
    storageBucket: 'uber-58114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDItFtJH9Q28yJFWeDz9O1OwdKvc5-2SY',
    appId: '1:65617778915:ios:f57ab53ef5c43f510f4dd6',
    messagingSenderId: '65617778915',
    projectId: 'uber-58114',
    databaseURL: 'https://uber-58114.firebaseio.com',
    storageBucket: 'uber-58114.appspot.com',
    iosBundleId: 'com.example.cvProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDItFtJH9Q28yJFWeDz9O1OwdKvc5-2SY',
    appId: '1:65617778915:ios:f57ab53ef5c43f510f4dd6',
    messagingSenderId: '65617778915',
    projectId: 'uber-58114',
    databaseURL: 'https://uber-58114.firebaseio.com',
    storageBucket: 'uber-58114.appspot.com',
    iosBundleId: 'com.example.cvProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4kdKa-49djFcvG-KfnGsfpvua5chCa_g',
    appId: '1:65617778915:web:a3cd8eb3bad397310f4dd6',
    messagingSenderId: '65617778915',
    projectId: 'uber-58114',
    authDomain: 'uber-58114.firebaseapp.com',
    databaseURL: 'https://uber-58114.firebaseio.com',
    storageBucket: 'uber-58114.appspot.com',
  );
}
